/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOptionalTerm extends PTerm
{
    private PTerm _term_;
    private TQuestionmark _questionmark_;

    public AOptionalTerm()
    {
        // Constructor
    }

    public AOptionalTerm(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") TQuestionmark _questionmark_)
    {
        // Constructor
        setTerm(_term_);

        setQuestionmark(_questionmark_);

    }

    @Override
    public Object clone()
    {
        return new AOptionalTerm(
            cloneNode(this._term_),
            cloneNode(this._questionmark_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOptionalTerm(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public TQuestionmark getQuestionmark()
    {
        return this._questionmark_;
    }

    public void setQuestionmark(TQuestionmark node)
    {
        if(this._questionmark_ != null)
        {
            this._questionmark_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._questionmark_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._questionmark_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._questionmark_ == child)
        {
            this._questionmark_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._questionmark_ == oldChild)
        {
            setQuestionmark((TQuestionmark) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
