/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASequenceExp extends PExp
{
    private PExp _exp_;
    private TWhitespace _whitespace_;
    private PTerm _term_;

    public ASequenceExp()
    {
        // Constructor
    }

    public ASequenceExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TWhitespace _whitespace_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setExp(_exp_);

        setWhitespace(_whitespace_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new ASequenceExp(
            cloneNode(this._exp_),
            cloneNode(this._whitespace_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TWhitespace getWhitespace()
    {
        return this._whitespace_;
    }

    public void setWhitespace(TWhitespace node)
    {
        if(this._whitespace_ != null)
        {
            this._whitespace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whitespace_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._whitespace_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._whitespace_ == child)
        {
            this._whitespace_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._whitespace_ == oldChild)
        {
            setWhitespace((TWhitespace) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
