/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import node.AAlternativeTerm;
import node.AFactorTerm;
import node.ANestedFactor;
import node.AOneormoreTerm;
import node.AOptionalTerm;
import node.AOrthogonalTerm;
import node.ASequenceExp;
import node.AStateFactor;
import node.ATermExp;
import node.AZeroormoreTerm;
import node.Node;
import node.Start;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPExp().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inATermExp(ATermExp node)
    {
        defaultIn(node);
    }

    public void outATermExp(ATermExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermExp(ATermExp node)
    {
        inATermExp(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermExp(node);
    }

    public void inASequenceExp(ASequenceExp node)
    {
        defaultIn(node);
    }

    public void outASequenceExp(ASequenceExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASequenceExp(ASequenceExp node)
    {
        inASequenceExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getWhitespace() != null)
        {
            node.getWhitespace().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outASequenceExp(node);
    }

    public void inAFactorTerm(AFactorTerm node)
    {
        defaultIn(node);
    }

    public void outAFactorTerm(AFactorTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactorTerm(AFactorTerm node)
    {
        inAFactorTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAFactorTerm(node);
    }

    public void inAAlternativeTerm(AAlternativeTerm node)
    {
        defaultIn(node);
    }

    public void outAAlternativeTerm(AAlternativeTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAlternativeTerm(AAlternativeTerm node)
    {
        inAAlternativeTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAAlternativeTerm(node);
    }

    public void inAOrthogonalTerm(AOrthogonalTerm node)
    {
        defaultIn(node);
    }

    public void outAOrthogonalTerm(AOrthogonalTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrthogonalTerm(AOrthogonalTerm node)
    {
        inAOrthogonalTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAOrthogonalTerm(node);
    }

    public void inAZeroormoreTerm(AZeroormoreTerm node)
    {
        defaultIn(node);
    }

    public void outAZeroormoreTerm(AZeroormoreTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAZeroormoreTerm(AZeroormoreTerm node)
    {
        inAZeroormoreTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getTimes() != null)
        {
            node.getTimes().apply(this);
        }
        outAZeroormoreTerm(node);
    }

    public void inAOneormoreTerm(AOneormoreTerm node)
    {
        defaultIn(node);
    }

    public void outAOneormoreTerm(AOneormoreTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOneormoreTerm(AOneormoreTerm node)
    {
        inAOneormoreTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        outAOneormoreTerm(node);
    }

    public void inAOptionalTerm(AOptionalTerm node)
    {
        defaultIn(node);
    }

    public void outAOptionalTerm(AOptionalTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOptionalTerm(AOptionalTerm node)
    {
        inAOptionalTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getQuestionmark() != null)
        {
            node.getQuestionmark().apply(this);
        }
        outAOptionalTerm(node);
    }

    public void inAStateFactor(AStateFactor node)
    {
        defaultIn(node);
    }

    public void outAStateFactor(AStateFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStateFactor(AStateFactor node)
    {
        inAStateFactor(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAStateFactor(node);
    }

    public void inANestedFactor(ANestedFactor node)
    {
        defaultIn(node);
    }

    public void outANestedFactor(ANestedFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANestedFactor(ANestedFactor node)
    {
        inANestedFactor(node);
        if(node.getLparen() != null)
        {
            node.getLparen().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getRparen() != null)
        {
            node.getRparen().apply(this);
        }
        outANestedFactor(node);
    }
}
